# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54e22cb87fd88fb7480be6c3e295ae9ae924a9d69b1b60103806dafc0ba37e93e9c387240abbb7c8ada82d05f5ea80a59a41aa0f5aac552967baac60c6574742

test:
  secret_key_base: 765f14c68d2dd01d260eb52b7854a5f0c1415ac36495732e99684c9bced1d4cc3a14c0851392c890e5c2f6bbf818e787724e4eda3d9de6cb7cb2aa22b9f5e93b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
